services:
  api:
    image: api:python
    container_name: api.fastapi_app
    build:
      context: .
      dockerfile: Dockerfile-Prod
#    volumes:
#      - .:/fastapi_app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/utils/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5
